projects:
    app:
        schemPath: src/schema.graphql
        extensions:
            endpoints:
            default: http://localhost:4000
    prisma:
        schemaPath: prisma/generated/prisma.graphql
        extensions:
            prisma: src/prisma.yml